### ISSUE TITLE
Images Array Problem

### ISSUE THREAD

**Issue by nohraay** [opalorange/OpalImagePicker#1]
Hello
I have a problem with the images array given in didFinishPickingImages function,
If I select one image, array count return 1, then I open Library again and I select a new image with the first one, array count return 3 instead of 2.

Thank you

**Comment by opalorange** [comment]
@nohraay Oh I see. Maybe you are retaining the instance of the Image Picker Controller. I can look into that.

**Comment by opalorange** [comment]
@nohraay see version 1.1.1

**Comment by nohraay** [comment]
Thank you for your fast reply

**Comment by appvicky** [comment]
Hello, I have updated the latest version 1.1.1. But the problem still seems to persist. I have resolved the issue by adding the line below,
selectedIndexPaths = []
