### ISSUE TITLE
change title 

### ISSUE THREAD

**Issue by DevFatani** [opalorange/OpalImagePicker#10]
hi i want to change the title and the two items (done, cancel) to another language how can i do this?
<img width="268" alt="screen shot 2017-09-02 at 10 31 21 am" src="https://user-images.githubusercontent.com/14845813/29993795-e93dcc2e-8fc9-11e7-861d-fbc1d1502448.png">

**Comment by opalorange** [comment]
Done and Cancel are iOS system buttons, so you don't need to convert them. They will change with the language on the user's device. You can change "Photos" by inserting an `OpalImagePickerConfiguration` into the picker and changing the `navigationTitle` to whatever you like.

**Comment by DevFatani** [comment]
this is iphone in arabic language but the change of (cancel, done) not happend
<img width="281" alt="screen shot 2017-09-03 at 8 24 33 am" src="https://user-images.githubusercontent.com/14845813/30000811-68f68ba6-9081-11e7-9dbb-08c4fb95c997.png">
