### ISSUE TITLE
navigation bar item localize

### ISSUE THREAD

**Issue by DevFatani** [opalorange/OpalImagePicker#11]
this is iPhone in Arabic language but the change of (cancel, done) not happened
<img width="281" alt="screen shot 2017-09-03 at 8 24 33 am" src="https://user-images.githubusercontent.com/14845813/30045880-8384627e-920f-11e7-8186-b34b4a9b194e.png">

**Comment by opalorange** [comment]
Okay thanks, I will take a closer look at this.

**Comment by opalorange** [comment]
Fixed. I added configurations to `OpalImagePickerConfiguration`, so you can change 'Cancel' and 'Done' buttons to any localization of your choice.
