### ISSUE TITLE
Order of assets in completion handler

### ISSUE THREAD

**Issue by bendodson** [opalorange/OpalImagePicker#12]
Can you let me know how the assets are being sorted when displayed in the completion handler? The image picker displays my images in date descending order but after I've picked them they come out in a different order which I can't quite work out (doesn't appear to be date ascending or descending). Ideally I'd like a way to specify image order (i.e. first image selected is first, second image selected is second, etc).

Thanks!

**Comment by opalorange** [comment]
Which completion handler are you using? This one `presentOpalImagePickerController(_:animated:select:cancel:)`?

**Comment by bendodson** [comment]
Yup, `presentOpalImagePickerController(_:animated:select:cancel:)`

**Comment by opalorange** [comment]
I am using the `UICollectionView` `indexPathsForSelectedItems` to determine the ordering of the `PHAsset` objects. I will look into how this can be fixed.

**Comment by bendodson** [comment]
Ah, that would explain it. `indexPathsForSelectedItems` is a bit weird with sort order. In previous apps that I've written that run into this problem, I've had to maintain selection state separately (i.e. sending an array across with the selected indexes and then sorting the results based on that).

**Comment by opalorange** [comment]
Fixed. See latest release. Now, the ordering is based on the order that the selections are made.

**Comment by bendodson** [comment]
Wonderful - thanks!
