### ISSUE TITLE
Seems it does not support deployment target 8.0

### ISSUE THREAD

**Issue by vishundayal** [opalorange/OpalImagePicker#13]
When I added     pod 'OpalImagePicker' in podfile, I get error 

> Specs satisfying the `OpalImagePicker` dependency were found, but they required a higher minimum deployment target.

My App has deployment target as 8.0 
Can you please advise if I can use with deployment target 8.0

**Comment by opalorange** [comment]
Currently you need iOS 9+ to use it, but I can investigate what it would take to support iOS 8.

**Comment by opalorange** [comment]
Fixed please see version 1.6.0
