### ISSUE TITLE
Unable to distinguish between images and videos in picker

### ISSUE THREAD

**Issue by michafaw** [opalorange/OpalImagePicker#14]
With the current display method for videos in the picker (a single frame image) it is not possible to distinguish between an image and a video while picking assets. A simple icon like a play button, camera icon (like Photos.app), and/or video runtime overlaid across the image would go far towards usability.
Even further would be allowing this to be a configurable icon via OpalImagePickerConfiguration.

**Comment by opalorange** [comment]
Good idea. I can take a look.

**Comment by opalorange** [comment]
Good idea, I can take a look.

**Comment by opalorange** [comment]
Added time labels to video content in 1.7.0.
