### ISSUE TITLE
Can this library used with objective-c projects

### ISSUE THREAD

**Issue by burhan1875** [opalorange/OpalImagePicker#15]
Hello,
i have an existing objective-c project. 
Is it possible to use this fantastic library with objective-c project ?
Many thanks in advance.

**Comment by michafaw** [comment]
Yep, we're using it with ours. Works great.

**Comment by burhan1875** [comment]
Hi,
thanks for your Message. Can you please tell me how to use it with an existing objektive-c project?

**Comment by opalorange** [comment]
Are you using Cocoapods?

**Comment by burhan1875** [comment]
NO ı am not using pods. But i think i can use it that should be no Problem

**Comment by opalorange** [comment]
Well, you can copy in the Swift classes or use Cocoapods, but if it is using Swift 4 you need to have Objective-C Inference set to 'YES' in your build settings.

**Comment by burhan1875** [comment]
Do i need a Bridge file? I dont know how to Import and then use it with objektive-c call? Thanks

**Comment by opalorange** [comment]
A Bridge file is for Objective-C code being used in Swift, so no for this code. Swift headers are created by the compiler for use in Objective-C. If you turn on the setting I specified above, you will get this header created properly.

**Comment by burhan1875** [comment]
Many thanks for your answer ist will try it.
