### ISSUE TITLE
Retrieve original size image

### ISSUE THREAD

**Issue by Aryal-Nischal** [opalorange/OpalImagePicker#16]
I am not able to extract original image size. The image gets resized when i debug it inside the delegate method. Any solution for this?

**Comment by opalorange** [comment]
Have you tried using the callback with the `PHAsset`? That will give you more control. Here is the Swift function below. You can use the `selectAssets:(([PHAsset]) -> Void)` closure to convert to `UIImage` and also get additional information about the Photo/Video.

`presentOpalImagePickerController(_ imagePicker: OpalImagePickerController, animated: Bool, maximumSelectionsAllowed: Int = 10, numberOfExternalItems: Int, externalItemsTitle: String, externalURLForIndex: @escaping (Int) -> URL?, selectImages: (([UIImage]) -> Void)? = nil, selectAssets: (([PHAsset]) -> Void)? = nil, selectExternalURLs: (([URL]) -> Void)? = nil, cancel: @escaping () -> Void, completion: (() -> Void)? = nil)`
