### ISSUE TITLE
Cant change navBar background color and title text color

### ISSUE THREAD

**Issue by SlavcoPetkovski** [opalorange/OpalImagePicker#17]
Can you push new update for externalizing these 2 to be changeable? Same in the Configuration as it is for changing the text of the title.

**Comment by SlavcoPetkovski** [comment]
let textAttributes = [NSForegroundColorAttributeName: <custom color>]
        navigationController?.navigationBar.titleTextAttributes = textAttributes
        navigationController?.navigationBar.barTintColor = <custom second color>

something like this

**Comment by opalorange** [comment]
The `OpalImagePickerController` is the `UINavigationController`, so you should be able to simply run this customization code against your instance of `OpalImagePickerController`.
