### ISSUE TITLE
Get full images size instead of square crop?

### ISSUE THREAD

**Issue by sethsandaru** [opalorange/OpalImagePicker#20]
Hello OpalOrange,

Is there any chance to get full images size instead of square crop all the time?

Thanks

**Comment by opalorange** [comment]
Yeah, you will want to use the callbacks that give you the `PHAsset` object. Then, there are iOS SDK APIs to create whatever size image you want. My callback for `UIImage` is more of a fast-track for users that want to put something together faster without dealing with the more advanced APIs.
