### ISSUE TITLE
Navigation items, "Cancel", "Done", how to chante it?

### ISSUE THREAD

**Issue by pablofridman** [opalorange/OpalImagePicker#23]
Is there a way to change the text on both buttons?
"configuration.okayString"  does not work. 

Thanks! 
Great library!

**Comment by opalorange** [comment]
Cancel and Done can be changed in `configuration.doneButtonTitle` and `configuration.cancelButtonTitle`. `okayString` modifies the "OK" string for alert: "You cannot select more than 10 images".
