### ISSUE TITLE
Unable to assign MediaTypes in Objective C

### ISSUE THREAD

**Issue by jprossardalia** [opalorange/OpalImagePicker#25]
Hi,
I'm unable to set MediaTypes showing error Property 'allowedMediaTypes' not found on object of type 'OpalImagePickerController *'.

Code Smaple:
`NSSet *mediaType = [NSSet setWithObject:[NSNumber numberWithInt:PHAssetMediaTypeImage]];
    imagePicker.allowedMediaTypes = mediaType;`

**Comment by opalorange** [comment]
If you change the build setting on the Pod to `Swift 3 @objc Inference`, it will continue to work. I can look into adding @objc in a future release to public methods
