### ISSUE TITLE
How to get list of images without #delegate using , #presentOpalImagePickerController

### ISSUE THREAD

**Issue by 8109350789** [opalorange/OpalImagePicker#26]
Hello, 

I am using without delegate method, so I want to know when I getting images list after the finish

here is my code please check 

 presentOpalImagePickerController(imagePicker, animated: true, select: { (assets) in
            //Save Images, update UI
            
           
           
            
            
            
            
            //let getALLImg:[UIImage] = imagePicker.asset
            
//            var i:Int = 0
//            print(select)
//            for getImage in select
//            {
//                print(i)
//
//                switch i {
//                case 0:
//                    self.img_view1.image = getImage
//                case 1:
//                    self.img_view2.image = getImage
//                case 2:
//                    self.img_view3.image = getImage
//                default:
//                    print(i)
//                }
//                // print(getImage)
//                i = i + 1
//            }
            
            
            //Dismiss Controller
            imagePicker.dismiss(animated: true, completion: nil)
        }, cancel: {
            //Cancel action?
            
        })

**Comment by opalorange** [comment]
Take a look at `PHImageManager`. You can request `UIImage` for the target size you are wanting from the `PHAsset` objects. https://developer.apple.com/documentation/photos/phimagemanager
