### ISSUE TITLE
EXIF meta data remove from Image

### ISSUE THREAD

**Issue by Rahulss153** [opalorange/OpalImagePicker#27]
When i upload images on server using OpalImagePicker. Retrive same image from server  and show in app then image not show properly as per gallery image.  and there is no  EXIF meta data in image.

So how can i solve problem?

**Comment by opalorange** [comment]
The OpalImagePicker provides you with the same `PHAsset` you would get from Apple's SDK. Usually you would get a `UIImage` from `PHImageManager` and convert it to a JPEG `Data` object using `UIImageJPEGRepresentation(_:_:)`

**Comment by Chrischi81** [comment]
Iam also interested in EXIF data...
i use the delegate-method: func imagePicker(_ picker: OpalImagePickerController, didFinishPickingAssets assets: [PHAsset])

i can save an Image to directory (PNGRepresentation)  and a i can read the data from the asset (e.g. location). But how can i save the image WITH data to the documents directory (not gallery)? Is it possible to make an 1:1 copy of the image from the gallery to the documents directory?

**Comment by opalorange** [comment]
I looked around a little bit. It seems to be harder to do this with the `Photos` framework than the previous `ALAssets` framework. I came across a few things on StackOverflow, and here is one Github library you could try https://github.com/zakkhoyt/PHAsset-Utility
