### ISSUE TITLE
Hide / Disable Segment Control for external Items

### ISSUE THREAD

**Issue by Chrischi81** [opalorange/OpalImagePicker#28]
Hi,

i use your Picker and it works great. There is one last thing, that i can not solve.

I use your Picker like:
`let imagePicker = OpalImagePickerController()
imagePicker.imagePickerDelegate = self        
present(imagePicker, animated: true, completion: nil)`

https://ibb.co/bLsoJ8

How can i hide or disable the Segment Control for external Items? I dont want to use external Items

**Comment by opalorange** [comment]
You need to delete the `optional` delegate method `imagePickerTitleForExternalItems`. That determines whether or not the segmented control shows up on top.
