### ISSUE TITLE
uncheck images

### ISSUE THREAD

**Issue by lexuanquynh** [opalorange/OpalImagePicker#35]
I use a OpalImagePicker in a viewcontroller for multil collectionview. 
I want to uncheck images when present it again. please help me.

**Comment by opalorange** [comment]
@lexuanquynh Do you want to uncheck all the images? Or do you want to allow the users to deselect images they choose? Are you reusing the Image Picker?

**Comment by lexuanquynh** [comment]
can you help me make a function can do:
uncheck all images when it showing again?
