### ISSUE TITLE
Use of undeclared type 'PHAsset'

### ISSUE THREAD

**Issue by onusgit** [opalorange/OpalImagePicker#38]
```
OpalImagePickerControllerDelegate
let imagePicker = OpalImagePickerController()
imagePicker.imagePickerDelegate = self
```

![screen shot 2018-10-22 at 5 30 05 pm](https://user-images.githubusercontent.com/15248145/47291164-42093f80-d620-11e8-85eb-63fa242dd7f6.png)

**Comment by vinamelody** [comment]
you need to `import Photos`
