### ISSUE TITLE
Unable to get external images from photo library

### ISSUE THREAD

**Issue by yashwanthios** [opalorange/OpalImagePicker#43]
When i am selecting images from photo library it is showing to select images from local and external. But when i am selecting images from external images those are not loaded into my view.

Otherwise i want to remove selection from external library.
suggest me the solution.

**Comment by opalorange** [comment]
Make sure not to implement this delegate function if you don't want to use external images
`@objc optional func imagePickerNumberOfExternalItems(_ picker: OpalImagePickerController) -> Int`

This is optional, and not required. The framework looks for an implementation before creating the tab bar.
