### ISSUE TITLE
Done and Cancel buttons not visible

### ISSUE THREAD

**Issue by arvindsen14** [opalorange/OpalImagePicker#45]
Hi,

Done and cancel buttons are not visible when I am implementing the same in my view controller.
Any specific reason for this.

I have been trying all the possible solution, but still no luck. Please do needful and suggest the solution for this.

Best,
Arvind

**Comment by opalorange** [comment]
Hi,
Check your `UIAppearance` modifications. They should be visible by default. Otherwise, you are welcome to set the `UINavigationItem.leftItem` and `UINavigation.rightItem` `tintColor`s
