### ISSUE TITLE
Can't change the labels

### ISSUE THREAD

**Issue by eVerup** [opalorange/OpalImagePicker#46]
Hi and thanks for the lib ! 

I can't change title for all the buttons done, cancel, title .. Did i miss something ? 
Here is my code : 

            let imagePicker = OpalImagePickerController()
            
            imagePicker.maximumSelectionsAllowed = 5
            imagePicker.configuration?.cancelButtonTitle = "Retour"
            imagePicker.configuration?.doneButtonTitle = "Valider"
            imagePicker.configuration?.navigationTitle = "Galerie"
            imagePicker.configuration?.okayString = "Ok"
            imagePicker.configuration?.maximumSelectionsAllowedMessage = "Vous pouvez sélectionner jusqu'à 5 médias de votre galerie !"
            
            presentOpalImagePickerController(imagePicker, animated: true, .....

**Comment by opalorange** [comment]
You need to initialize the configuration object. It is `nil` by default

```swift
let imagePicker = OpalImagePickerController()
        
imagePicker.maximumSelectionsAllowed = 5
let configuration = OpalImagePickerConfiguration()
configuration.cancelButtonTitle = "Retour"
configuration.doneButtonTitle = "Valider"
configuration.navigationTitle = "Galerie"configuration?.okayString = "Ok"
configuration.maximumSelectionsAllowedMessage = "Vous pouvez sélectionner jusqu'à 5 médias de votre galerie !"
imagePicker.configuration = configuration
        
presentOpalImagePickerController(imagePicker, animated: true, .....
```
