### ISSUE TITLE
How to clear Previous images selection when present Picker?

### ISSUE THREAD

**Issue by StellarKuldeep** [opalorange/OpalImagePicker#48]
In my scenario, i allow user to delete multiple images from selection and the issue is that when user delete single image from selected image and then when he present picker again all selected images are selected even deleted image is also selected so i want to clear previous selection when user present picker.

I have put below code in `ViewDidLoad()`

```
imagePicker.imagePickerDelegate = self
imagePicker.selectionTintColor = UIColor.black.withAlphaComponent(0.5)
imagePicker.selectionImageTintColor = UIColor.white
imagePicker.statusBarPreference = UIStatusBarStyle.lightContent
imagePicker.maximumSelectionsAllowed = 5
imagePicker.allowedMediaTypes = Set([PHAssetMediaType.image])
```

I think writing above code in `UIButton` action is bad idea as it takes too much memory if i write above code in `UIButton` action.

**My Button Click Code.**

```
@IBAction func btnSelectImageTapped(_ sender: UIButton) {
        self.present(imagePicker, animated: true, completion: nil)
}
```
so please let me know how can i clear images selection?

Thanks in advance.

**Comment by opalorange** [comment]
Yeah, maybe would be better if you re-initialize the object instead of holding onto the reference after dismissing. Would also help your memory footprint in your app.
