### ISSUE TITLE
update 

### ISSUE THREAD

**Issue by alauthor** [opalorange/OpalImagePicker#56]
please update this pod 
imagePicker?(imagePicker, didFinishPickingImages: savedImages) -> this's deprecated . 
-----------------
'imagePicker(_:didFinishPickingImages:)' is deprecated: This function will be removed from future versions. Please switch to using `imagePicker(_,didFinishPickingAssets)`, and download `UIImage` using the `PHAsset` APIs.

**Comment by opalorange** [comment]
Fixed
