### ISSUE TITLE
Don't display videos 

### ISSUE THREAD

**Issue by ibhavin** [opalorange/OpalImagePicker#6]
I have integrated OpalImagePicker through cocoapods in my project.

I have several question regarding OpalImagePicker:
1) When I present OpalImagePicker it is also displaying video thumbnail along with all images. So how can I restrict it. (Video mediaType=2/0 and in image mediaType=1/0)
2) Is there any functionality for maximum selection?

**Comment by opalorange** [comment]
Hi, currently we don't have support for either of those two items in this library. I can work on an enhancement to add those two items.

**Comment by opalorange** [comment]
Hi, I addressed both of these issues in version 1.3.0. Please update your pod, and use the `maximumSelectionsAllowed` and `allowedMediaTypes` to control these behaviors.
