### ISSUE TITLE
Add support for custom albums?

### ISSUE THREAD

**Issue by novall** [opalorange/OpalImagePicker#8]
It would be awesome to be able to add in custom image data (e.g. selecting pre-fetched Facebook photos to display in the OpalImagePicker). Let me know if this might be on the roadmap! :)

**Comment by opalorange** [comment]
Hi novall. I don't have any plans to add this, but I am open to it. Would this require people to have a dependency on Facebook's Developer APIs?

**Comment by novall** [comment]
Hi Kris! If support is added to select either an array of Data (initialized with contents of a URL), or to take an array of UIImages, that would take care of custom albums from a Facebook graph request. No dependency required if developers don't want to use the FB SDK.

**Comment by opalorange** [comment]
Okay I can take a look at this. Thanks Novall

**Comment by opalorange** [comment]
Novall I was looking at this a little more closely. I think it would be better to use URLs because then I could download asynchronously while you are scrolling through the images as they are needed. With Data, you would have to initialize all of these from your application at one time. Does this sound like a better solution to you?

**Comment by novall** [comment]
Yes, URLs would be better in this case. Thanks again for looking into this!

**Comment by opalorange** [comment]
Novall, I released a new version of this pod (1.4.0), and I added support for this. Can you please test it out, and let me know your thoughts?

Thanks,
Kris

**Comment by novall** [comment]
Hey Kris - This is awesome! I tested the external image picker both via the Swift function and delegate methods for Facebook photos and they worked great on my end. One thing to add -- would it be a relatively quick change to make the segmented control optional/ hidden? For example, I'm presenting different library & camera options through an action sheet, so the extra step of the toggle isn't needed. I can also take a look at it and submit a PR this week if I have time!

**Comment by opalorange** [comment]
It depends on how performant we want it to be. I put in two `UICollectionView` to make a nice animation, the `collectionView` and `externalCollectionView`. I think it would be better to only have the `externalCollectionView` for this case.  It would also take additional work to make sure system doesn't ask permission to access the photo library in this case. We would need to make an optional setting for external only that doesn't affect other users of the library.
